export function buildAppScript(): string {
  return [
    "const app = document.getElementById('app');",
    "async function loadData() {",
    "  const inline = document.getElementById('transcript-data');",
    "  if (inline && inline.textContent) {",
    "    const data = JSON.parse(inline.textContent);",
    "    return { data, searchIndex: buildIndexFallback(data.messages || []) };",
    "  }",
    "  const response = await fetch('./data.json');",
    "  if (!response.ok) throw new Error('Could not load transcript data.json');",
    "  const data = await response.json();",
    "  let searchIndex = null;",
    "  try {",
    "    const indexResponse = await fetch('./search-index.json');",
    "    if (indexResponse.ok) {",
    "      searchIndex = await indexResponse.json();",
    "    }",
    "  } catch {",
    "    searchIndex = null;",
    "  }",
    "  return { data, searchIndex: searchIndex || buildIndexFallback(data.messages || []) };",
    "}",
    "function escapeHtml(value) {",
    "  return String(value)",
    "    .replace(/&/g, '&amp;')",
    "    .replace(/</g, '&lt;')",
    "    .replace(/>/g, '&gt;')",
    "    .replace(/\\\"/g, '&quot;')",
    "    .replace(/'/g, '&#039;');",
    "}",
    "function tokenize(value) {",
    "  const matches = String(value || '').toLowerCase().match(/[a-z0-9_@#.:/\\\\-]+/g) || [];",
    "  return Array.from(new Set(matches.filter((token) => token.length >= 2)));",
    "}",
    "function buildIndexFallback(messages) {",
    "  const tokenMap = {};",
    "  for (let i = 0; i < messages.length; i += 1) {",
    "    const msg = messages[i];",
    "    const tokens = tokenize((msg.author || '') + ' ' + (msg.authorId || '') + ' ' + (msg.contentText || '') + ' ' + (msg.id || ''));",
    "    for (const token of tokens) {",
    "      if (!tokenMap[token]) tokenMap[token] = [];",
    "      tokenMap[token].push(i);",
    "    }",
    "  }",
    "  return { tokenMap };",
    "}",
    "function intersectSortedUnique(left, right) {",
    "  const set = new Set(right);",
    "  const out = [];",
    "  for (const value of left) {",
    "    if (set.has(value)) out.push(value);",
    "  }",
    "  return Array.from(new Set(out));",
    "}",
    "function lookupWithIndex(searchIndex, query) {",
    "  if (!searchIndex || !searchIndex.tokenMap) return null;",
    "  const tokens = tokenize(query);",
    "  if (tokens.length === 0) return null;",
    "  let result = null;",
    "  for (const token of tokens) {",
    "    const hits = searchIndex.tokenMap[token] || [];",
    "    if (!result) {",
    "      result = Array.from(new Set(hits));",
    "      continue;",
    "    }",
    "    result = intersectSortedUnique(result, hits);",
    "    if (result.length === 0) break;",
    "  }",
    "  return result || [];",
    "}",
    "function renderAttachment(item) {",
    "  const src = item.dataUrl || item.localPath || item.url;",
    "  const type = item.contentType || '';",
    "  if (type.startsWith('image/')) return '<div class=\\\"attachment\\\"><img src=\\\"' + src + '\\\" alt=\\\"' + escapeHtml(item.filename) + '\\\"></div>';",
    "  if (type.startsWith('video/')) return '<div class=\\\"attachment\\\"><video src=\\\"' + src + '\\\" controls></video></div>';",
    "  if (type.startsWith('audio/')) return '<div class=\\\"attachment\\\"><audio src=\\\"' + src + '\\\" controls></audio></div>';",
    "  return '<div class=\\\"attachment\\\"><a href=\\\"' + src + '\\\" target=\\\"_blank\\\" rel=\\\"noreferrer\\\">' + escapeHtml(item.filename) + '</a></div>';",
    "}",
    "function renderMessages(data, query, searchIndex) {",
    "  const q = String(query || '').trim().toLowerCase();",
    "  let list = data.messages;",
    "  if (q) {",
    "    const indexed = lookupWithIndex(searchIndex, q);",
    "    if (indexed) {",
    "      list = indexed.map((index) => data.messages[index]).filter(Boolean);",
    "    } else {",
    "      list = data.messages.filter((msg) => msg.contentText.toLowerCase().includes(q) || msg.author.toLowerCase().includes(q) || msg.id.includes(q));",
    "    }",
    "  }",
    "  const html = list.map((msg) => {",
    "    const badges = [msg.pinned ? 'PINNED' : '', msg.deleted ? 'DELETED' : ''].filter(Boolean);",
    "    const attachments = msg.attachments.length ? '<div class=\\\"attachment-list\\\">' + msg.attachments.map(renderAttachment).join('') + '</div>' : '';",
    "    const embeds = msg.embeds.length ? msg.embeds.map((embed) => '<div class=\\\"embed\\\"><pre>' + escapeHtml(JSON.stringify(embed, null, 2)) + '</pre></div>').join('') : '';",
    "    const reactions = msg.reactions.length ? '<ul class=\\\"meta-list\\\">' + msg.reactions.map((reaction) => '<li>' + escapeHtml(JSON.stringify(reaction)) + '</li>').join('') + '</ul>' : '';",
    "    const avatar = msg.avatarUrl ? '<img class=\\\"avatar\\\" src=\\\"' + msg.avatarUrl + '\\\" alt=\\\"' + escapeHtml(msg.author) + '\\\">' : '<div class=\\\"avatar\\\"></div>';",
    "    const badgesHtml = badges.map((badge) => '<span class=\\\"badge\\\">' + badge + '</span>').join('');",
    "    return '<article class=\\\"message\\\" id=\\\"m-' + msg.id + '\\\" data-day=\\\"' + msg.dayKey + '\\\"><div>' + avatar + '</div><div><div class=\\\"author-row\\\"><span class=\\\"author\\\">' + escapeHtml(msg.author) + '</span><span class=\\\"time\\\">' + escapeHtml(msg.createdAt) + '</span>' + badgesHtml + '</div><div class=\\\"content\\\">' + msg.contentHtml + '</div>' + attachments + embeds + reactions + '</div></article>';",
    "  }).join('');",
    "  return { html, total: data.messages.length, visible: list.length };",
    "}",
    "function renderToc(data) {",
    "  if (!data.toc || data.toc.length === 0) return '';",
    "  const items = data.toc.map((entry) => '<li><a href=\\\"#day-' + entry.day + '\\\">' + entry.day + '</a> (' + entry.count + ')</li>').join('');",
    "  return '<nav class=\\\"toc\\\"><strong>Table of contents</strong><ul>' + items + '</ul></nav>';",
    "}",
    "function renderShell(data, searchIndex) {",
    "  const searchBlock = data.searchable ? '<input id=\\\"search\\\" placeholder=\\\"Search by content, author, or message ID\\\" aria-label=\\\"Search messages\\\">' : '';",
    "  const readonlyBanner = data.readOnly ? '<div class=\\\"readonly-banner\\\">Read-only export mode</div>' : '';",
    "  const chunkTag = data.chunk ? '<span class=\\\"badge\\\">Chunk ' + data.chunk.index + '/' + data.chunk.total + '</span>' : '';",
    "  app.innerHTML = '<header><div class=\\\"toolbar\\\"><h1>' + escapeHtml(data.title) + '</h1>' + chunkTag + searchBlock + '<div class=\\\"stats\\\" id=\\\"stats\\\"></div></div></header><main>' + readonlyBanner + renderToc(data) + '<section id=\\\"alerts\\\"></section><section id=\\\"messages\\\"></section></main>' + (data.watermark ? '<div class=\\\"watermark\\\">' + escapeHtml(data.watermark) + '</div>' : '');",
    "  if (data.accessibilityMode) document.body.classList.add('accessibility');",
    "  const alerts = document.getElementById('alerts');",
    "  const messagesEl = document.getElementById('messages');",
    "  const statsEl = document.getElementById('stats');",
    "  const input = document.getElementById('search');",
    "  const warnings = [...(data.warnings || []), ...(data.limitations || [])];",
    "  if (warnings.length) {",
    "    alerts.innerHTML = '<div class=\\\"embed\\\"><strong>Notes</strong><ul class=\\\"meta-list\\\">' + warnings.map((item) => '<li>' + escapeHtml(item) + '</li>').join('') + '</ul></div>';",
    "  }",
    "  function rerender() {",
    "    const result = renderMessages(data, input ? input.value : '', searchIndex);",
    "    messagesEl.innerHTML = result.html;",
    "    statsEl.textContent = result.visible + '/' + result.total + ' messages';",
    "  }",
    "  if (input) input.addEventListener('input', rerender);",
    "  rerender();",
    "}",
    "loadData().then(({ data, searchIndex }) => renderShell(data, searchIndex)).catch((error) => {",
    "  app.innerHTML = '<pre>' + escapeHtml(error && error.stack ? error.stack : String(error)) + '</pre>';",
    "});",
  ].join("\n");
}
