export function buildAppScript(): string {
  return [
    "const app = document.getElementById('app');",
    "async function loadData() {",
    "  const inline = document.getElementById('transcript-data');",
    "  if (inline && inline.textContent) {",
    "    const data = JSON.parse(inline.textContent);",
    "    return { data, searchIndex: buildIndexFallback(data.messages || []) };",
    "  }",
    "  const response = await fetch('./data.json');",
    "  if (!response.ok) throw new Error('Could not load transcript data.json');",
    "  const data = await response.json();",
    "  let searchIndex = null;",
    "  try {",
    "    const indexResponse = await fetch('./search-index.json');",
    "    if (indexResponse.ok) {",
    "      searchIndex = await indexResponse.json();",
    "    }",
    "  } catch {",
    "    searchIndex = null;",
    "  }",
    "  return { data, searchIndex: searchIndex || buildIndexFallback(data.messages || []) };",
    "}",
    "function escapeHtml(value) {",
    "  return String(value)",
    "    .replace(/&/g, '&amp;')",
    "    .replace(/</g, '&lt;')",
    "    .replace(/>/g, '&gt;')",
    "    .replace(/\\\"/g, '&quot;')",
    "    .replace(/'/g, '&#039;');",
    "}",
    "function tokenize(value) {",
    "  const matches = String(value || '').toLowerCase().match(/[a-z0-9_@#.:/\\\\-]+/g) || [];",
    "  return Array.from(new Set(matches.filter((token) => token.length >= 2)));",
    "}",
    "function buildIndexFallback(messages) {",
    "  const tokenMap = {};",
    "  for (let i = 0; i < messages.length; i += 1) {",
    "    const msg = messages[i];",
    "    const tokens = tokenize((msg.author || '') + ' ' + (msg.authorId || '') + ' ' + (msg.contentText || '') + ' ' + (msg.id || ''));",
    "    for (const token of tokens) {",
    "      if (!tokenMap[token]) tokenMap[token] = [];",
    "      tokenMap[token].push(i);",
    "    }",
    "  }",
    "  return { tokenMap };",
    "}",
    "function intersectSortedUnique(left, right) {",
    "  const set = new Set(right);",
    "  const out = [];",
    "  for (const value of left) {",
    "    if (set.has(value)) out.push(value);",
    "  }",
    "  return Array.from(new Set(out));",
    "}",
    "function lookupWithIndex(searchIndex, query) {",
    "  if (!searchIndex || !searchIndex.tokenMap) return null;",
    "  const tokens = tokenize(query);",
    "  if (tokens.length === 0) return null;",
    "  let result = null;",
    "  for (const token of tokens) {",
    "    const hits = searchIndex.tokenMap[token] || [];",
    "    if (!result) {",
    "      result = Array.from(new Set(hits));",
    "      continue;",
    "    }",
    "    result = intersectSortedUnique(result, hits);",
    "    if (result.length === 0) break;",
    "  }",
    "  return result || [];",
    "}",
    "function renderAttachment(item) {",
    "  const src = item.dataUrl || item.localPath || item.url;",
    "  const type = item.contentType || '';",
    "  if (type.startsWith('image/')) return '<div class=\\\"attachment\\\"><img src=\\\"' + src + '\\\" alt=\\\"' + escapeHtml(item.filename) + '\\\"></div>';",
    "  if (type.startsWith('video/')) return '<div class=\\\"attachment\\\"><video src=\\\"' + src + '\\\" controls></video></div>';",
    "  if (type.startsWith('audio/')) return '<div class=\\\"attachment\\\"><audio src=\\\"' + src + '\\\" controls></audio></div>';",
    "  return '<div class=\\\"attachment\\\"><a href=\\\"' + src + '\\\" target=\\\"_blank\\\" rel=\\\"noreferrer\\\">' + escapeHtml(item.filename) + '</a></div>';",
    "}",
    "function formatTimestamp(iso) {",
    "  const d = new Date(iso);",
    "  if (isNaN(d.getTime())) return escapeHtml(iso);",
    "  return d.toLocaleString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit', hour: 'numeric', minute: '2-digit', hour12: true });",
    "}",
    "function formatCompactTime(iso) {",
    "  const d = new Date(iso);",
    "  if (isNaN(d.getTime())) return escapeHtml(iso);",
    "  return d.toLocaleString(undefined, { hour: 'numeric', minute: '2-digit', hour12: true });",
    "}",
    "function renderEmbed(embed) {",
    "  let html = '<div class=\\\"embed\\\"><div class=\\\"embed-content-wrap\\\"><div class=\\\"embed-main\\\">';",
    "  if (embed.author) {",
    "    const icon = embed.author.icon_url || embed.author.proxy_icon_url;",
    "    html += '<div class=\\\"embed-author\\\">' + (icon ? '<img src=\\\"' + escapeHtml(icon) + '\\\" class=\\\"embed-author-icon\\\">' : '') + escapeHtml(embed.author.name) + '</div>';",
    "  }",
    "  if (embed.title) html += '<div class=\\\"embed-title\\\">' + escapeHtml(embed.title) + '</div>';",
    "  if (embed.description) html += '<div class=\\\"embed-description\\\">' + escapeHtml(embed.description) + '</div>';",
    "  if (embed.fields && embed.fields.length) {",
    "    html += '<div class=\\\"embed-fields\\\">' + embed.fields.map(f => '<div class=\\\"embed-field ' + (f.inline ? 'inline' : '') + '\\\"><div class=\\\"embed-field-name\\\">' + escapeHtml(f.name) + '</div><div class=\\\"embed-field-value\\\">' + escapeHtml(f.value) + '</div></div>').join('') + '</div>';",
    "  }",
    "  if (embed.image) {",
    "    const src = embed.image.url || embed.image.proxy_url;",
    "    if (src) html += '<img src=\\\"' + escapeHtml(src) + '\\\" class=\\\"embed-image\\\">';",
    "  }",
    "  if (embed.footer || embed.timestamp) {",
    "    html += '<div class=\\\"embed-footer\\\">';",
    "    if (embed.footer && embed.footer.icon_url) html += '<img src=\\\"' + escapeHtml(embed.footer.icon_url) + '\\\" class=\\\"embed-footer-icon\\\">';",
    "    if (embed.footer && embed.footer.text) html += '<span>' + escapeHtml(embed.footer.text) + '</span>';",
    "    if (embed.timestamp) html += (embed.footer && embed.footer.text ? '<span style=\\\"margin:0 4px;\\\">•</span>' : '') + formatTimestamp(embed.timestamp);",
    "    html += '</div>';",
    "  }",
    "  html += '</div>';",
    "  if (embed.thumbnail) {",
    "    const src = embed.thumbnail.url || embed.thumbnail.proxy_url;",
    "    if (src) html += '<img src=\\\"' + escapeHtml(src) + '\\\" class=\\\"embed-thumbnail\\\">';",
    "  }",
    "  return html + '</div></div>';",
    "}",
    "function renderReaction(r) {",
    "  const emoji = r.emoji.id ? '<img src=\\\"https://cdn.discordapp.com/emojis/' + r.emoji.id + '.png\\\" class=\\\"reaction-emoji\\\">' : '<span class=\\\"reaction-emoji\\\">' + escapeHtml(r.emoji.name) + '</span>';",
    "  return '<div class=\\\"reaction ' + (r.me ? 'me' : '') + '\\\">' + emoji + '<div class=\\\"reaction-count\\\">' + r.count + '</div></div>';",
    "}",
    "function renderMessages(data, query, searchIndex) {",
    "  const q = String(query || '').trim().toLowerCase();",
    "  let list = data.messages;",
    "  if (q) {",
    "    const indexed = lookupWithIndex(searchIndex, q);",
    "    if (indexed) {",
    "      list = indexed.map((index) => data.messages[index]).filter(Boolean);",
    "    } else {",
    "      list = data.messages.filter((msg) => msg.contentText.toLowerCase().includes(q) || msg.author.toLowerCase().includes(q) || msg.id.includes(q));",
    "    }",
    "  }",
    "  let html = '';",
    "  let lastAuthorId = null;",
    "  let lastTime = null;",
    "  for (let i = 0; i < list.length; i++) {",
    "    const msg = list[i];",
    "    const isNewDay = !q && msg.dayKey !== (list[i-1] ? list[i-1].dayKey : null);",
    "    if (isNewDay) {",
    "      html += '<div class=\"divider\" id=\"day-' + msg.dayKey + '\"><span class=\"divider-content\">' + escapeHtml(msg.dayKey) + '</span></div>';",
    "    }",
    "    const t = new Date(msg.createdAt);",
    "    const lt = lastTime ? new Date(lastTime) : null;",
    "    const isGrouped = !q && msg.authorId === lastAuthorId && lt && (t - lt < 300000);",
    "    const badges = [msg.pinned ? 'PINNED' : '', msg.deleted ? 'DELETED' : ''].filter(Boolean);",
    "    const attachments = msg.attachments.length ? '<div class=\\\"attachment-list\\\">' + msg.attachments.map(renderAttachment).join('') + '</div>' : '';",
    "    const embeds = msg.embeds.length ? msg.embeds.map(renderEmbed).join('') : '';",
    "    const reactions = msg.reactions.length ? '<div class=\\\"reactions-row\\\">' + msg.reactions.map(renderReaction).join('') + '</div>' : '';",
    "    const badgesHtml = badges.map((badge) => '<span class=\"badge\\\">' + badge + '</span>').join('');",
    "    if (isGrouped) {",
    "      const compactTime = formatCompactTime(msg.createdAt);",
    "      html += '<article class=\\\"message message-grouped\\\" id=\\\"m-' + msg.id + '\\\"><div class=\\\"message-compact-gutter\\\"><span class=\\\"message-timestamp-compact\\\">' + compactTime + '</span></div><div class=\\\"message-content-wrap\\\"><div class=\\\"content\\\">' + msg.contentHtml + '</div>' + attachments + embeds + reactions + '</div></article>';",
    "    } else {",
    "      const avatar = msg.avatarUrl ? '<img class=\\\"avatar\\\" src=\\\"' + msg.avatarUrl + '\\\" alt=\\\"' + escapeHtml(msg.author) + '\\\">' : '<div class=\\\"avatar\\\">' + escapeHtml(msg.author.charAt(0)) + '</div>';",
    "      html += '<article class=\\\"message\\\" id=\\\"m-' + msg.id + '\\\"><div class=\\\"message-gutter\\\">' + avatar + '</div><div class=\\\"message-content-wrap\\\"><div class=\\\"author-row\\\"><span class=\\\"author\\\">' + escapeHtml(msg.author) + '</span><span class=\\\"time\\\">' + formatTimestamp(msg.createdAt) + '</span>' + badgesHtml + '</div><div class=\\\"content\\\">' + msg.contentHtml + '</div>' + attachments + embeds + reactions + '</div></article>';",
    "    }",
    "    lastAuthorId = msg.authorId;",
    "    lastTime = msg.createdAt;",
    "  }",
    "  return { html, total: data.messages.length, visible: list.length };",
    "}",
    "function renderToc(data) {",
    "  if (!data.toc || data.toc.length === 0) return '';",
    "  const items = data.toc.map((entry) => '<li><a href=\\\"#day-' + entry.day + '\\\">' + entry.day + '</a> (' + entry.count + ')</li>').join('');",
    "  return '<nav class=\\\"toc\\\"><strong>Table of contents</strong><ul>' + items + '</ul></nav>';",
    "}",
    "function renderServerList(data) {",
    "  if (!data.guild || (data.panels && !data.panels.serverList)) return '';",
    "  const g = data.guild;",
    "  const icon = g.iconUrl ? '<img src=\\\"' + g.iconUrl + '\\\" alt=\\\"\\\" class=\\\"server-icon\\\">' : '<div class=\\\"server-icon server-icon-placeholder\\\">' + (g.name ? escapeHtml(g.name.charAt(0)) : '?') + '</div>';",
    "  return '<aside class=\\\"server-list\\\" aria-label=\\\"Servers\\\"><div class=\\\"server-pill-wrap\\\"><div class=\\\"server-pill\\\">' + icon + '</div></div></aside>';",
    "}",
    "function renderChannelList(data) {",
    "  if (!data.channels || !data.channel) return '';",
    "  const currentId = data.channel.id;",
    "  const byParent = {};",
    "  for (const ch of data.channels) {",
    "    const pid = ch.parentId || 'none';",
    "    if (!byParent[pid]) byParent[pid] = [];",
    "    byParent[pid].push(ch);",
    "  }",
    "  let html = '';",
    "  const root = byParent['none'] || [];",
    "  for (const ch of root) {",
    "    const isCategory = byParent[ch.id] && byParent[ch.id].length > 0;",
    "    if (isCategory) {",
    "      html += '<div class=\\\"channel-category\\\">' + escapeHtml(ch.name || ch.id) + '</div>';",
    "      const children = byParent[ch.id] || [];",
    "      for (const sub of children) {",
    "        const active = sub.id === currentId ? ' channel-item-active' : '';",
    "        html += '<a href=\\\"#\\\" class=\\\"channel-item' + active + '\\\" data-channel-id=\\\"' + escapeHtml(sub.id) + '\\\"><span class=\\\"channel-hash\\\">#</span>' + escapeHtml(sub.name || sub.id) + '</a>';",
    "      }",
    "    } else {",
    "      const active = ch.id === currentId ? ' channel-item-active' : '';",
    "      html += '<a href=\\\"#\\\" class=\\\"channel-item' + active + '\\\" data-channel-id=\\\"' + escapeHtml(ch.id) + '\\\"><span class=\\\"channel-hash\\\">#</span>' + escapeHtml(ch.name || ch.id) + '</a>';",
    "    }",
    "  }",
    "  return '<aside class=\\\"channel-list\\\" aria-label=\\\"Channels\\\"><div class=\\\"channel-list-header\\\">' + escapeHtml(data.guild ? data.guild.name || 'Server' : 'Channels') + '<svg width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" style=\\\"margin-left:auto;flex-shrink:0;color:var(--header-secondary)\\\"><path fill=\\\"currentColor\\\" d=\\\"M5.3 9.3a1 1 0 0 1 1.4 0L12 14.58l5.3-5.3a1 1 0 1 1 1.4 1.42l-6 6a1 1 0 0 1-1.4 0l-6-6a1 1 0 0 1 0-1.42Z\\\"></path></svg></div><nav class=\\\"channel-nav\\\">' + html + '</nav></aside>';",
    "}",
    "function renderMembersSidebar(data) {",
    "  if (!data.members || data.members.length === 0 || (data.panels && !data.panels.membersSidebar)) return '';",
    "  var bots = []; var humans = [];",
    "  for (var mi = 0; mi < data.members.length; mi++) {",
    "    if (data.members[mi].bot) bots.push(data.members[mi]);",
    "    else humans.push(data.members[mi]);",
    "  }",
    "  function renderMember(m) {",
    "    var name = m.globalName || m.username || m.id;",
    "    var avatar = m.avatarUrl ? '<img src=\\\"' + m.avatarUrl + '\\\" alt=\\\"\\\" class=\\\"member-avatar\\\">' : '<div class=\\\"member-avatar member-avatar-placeholder\\\">' + escapeHtml((name || '?').charAt(0)) + '</div>';",
    "    var botTag = m.bot ? '<span class=\\\"member-bot\\\">APP</span>' : '';",
    "    return '<div class=\\\"member-row\\\"><span class=\\\"member-avatar-wrap\\\">' + avatar + '</span><span class=\\\"member-name\\\">' + escapeHtml(name) + '</span>' + botTag + '</div>';",
    "  }",
    "  var html = '';",
    "  if (humans.length > 0) {",
    "    html += '<div class=\\\"members-header\\\">Online \\u2014 ' + humans.length + '</div>';",
    "    html += humans.map(renderMember).join('');",
    "  }",
    "  if (bots.length > 0) {",
    "    html += '<div class=\\\"members-header\\\">Bots \\u2014 ' + bots.length + '</div>';",
    "    html += bots.map(renderMember).join('');",
    "  }",
    "  return '<aside class=\\\"members-sidebar\\\" aria-label=\\\"Members\\\"><div class=\\\"members-list\\\">' + html + '</div></aside>';",
    "}",
    "function renderShell(data, searchIndex) {",
    "  const searchBlock = data.searchable ? '<input id=\\\"search\\\" placeholder=\\\"Search by content\\\" aria-label=\\\"Search messages\\\">' : '';",
    "  const readonlyBanner = data.readOnly ? '<div class=\\\"readonly-banner\\\">Read-only export</div>' : '';",
    "  const chunkTag = data.chunk ? '<span class=\\\"badge\\\">Chunk ' + data.chunk.index + '/' + data.chunk.total + '</span>' : '';",
    "  const channelName = (data.channel && data.channel.name) ? data.channel.name : data.title.replace(/^Transcript:\\\\s*/, '');",
    "  const mainHeader = '<header class=\\\"main-header\\\"><div class=\\\"toolbar\\\"><h1 class=\\\"channel-title\\\">#' + escapeHtml(channelName) + '</h1>' + chunkTag + searchBlock + '<div class=\\\"stats\\\" id=\\\"stats\\\"></div></div></header>';",
    "  const mainContent = '<main class=\\\"main-content\\\">' + readonlyBanner + renderToc(data) + '<section id=\\\"alerts\\\"></section><section id=\\\"messages\\\"></section></main>';",
    "  const p = data.panels || { serverList: true, channelList: true, membersSidebar: true };",
    "  const hasFullUi = data.guild && (data.channels || data.members) && (p.serverList || p.channelList || p.membersSidebar);",
    "  if (hasFullUi) {",
    "    document.body.classList.add('discord-ui-layout');",
    "    app.innerHTML = '<div class=\\\"discord-ui\\\">' + renderServerList(data) + renderChannelList(data) + '<div class=\\\"main-area\\\">' + mainHeader + mainContent + '</div>' + renderMembersSidebar(data) + '</div>' + (data.watermark ? '<div class=\\\"watermark\\\">' + escapeHtml(data.watermark) + '</div>' : '');",
    "  } else {",
    "    document.body.classList.remove('discord-ui-layout');",
    "    app.innerHTML = '<header><div class=\\\"toolbar\\\"><h1>' + escapeHtml(data.title) + '</h1>' + chunkTag + searchBlock + '<div class=\\\"stats\\\" id=\\\"stats\\\"></div></div></header><main>' + readonlyBanner + renderToc(data) + '<section id=\\\"alerts\\\"></section><section id=\\\"messages\\\"></section></main>' + (data.watermark ? '<div class=\\\"watermark\\\">' + escapeHtml(data.watermark) + '</div>' : '');",
    "  }",
    "  if (data.accessibilityMode) document.body.classList.add('accessibility');",
    "  const alerts = document.getElementById('alerts');",
    "  const messagesEl = document.getElementById('messages');",
    "  const statsEl = document.getElementById('stats');",
    "  const input = document.getElementById('search');",
    "  const warnings = [...(data.warnings || []), ...(data.limitations || [])];",
    "  if (alerts && warnings.length) {",
    "    alerts.innerHTML = '<div class=\\\"embed\\\"><strong>Notes</strong><ul class=\\\"meta-list\\\">' + warnings.map((item) => '<li>' + escapeHtml(item) + '</li>').join('') + '</ul></div>';",
    "  }",
    "  function rerender() {",
    "    const result = renderMessages(data, input ? input.value : '', searchIndex);",
    "    if (messagesEl) {",
    "      messagesEl.innerHTML = result.html;",
    "      const mainContentEl = document.querySelector('.main-content');",
    "      if (mainContentEl && !input?.value) {",
    "        mainContentEl.scrollTop = mainContentEl.scrollHeight;",
    "      }",
    "    }",
    "    if (statsEl) statsEl.textContent = result.visible + '/' + result.total + ' messages';",
    "  }",
    "  if (input) input.addEventListener('input', rerender);",
    "  rerender();",
    "}",
    "loadData().then(({ data, searchIndex }) => renderShell(data, searchIndex)).catch((error) => {",
    "  app.innerHTML = '<pre>' + escapeHtml(error && error.stack ? error.stack : String(error)) + '</pre>';",
    "});",
  ].join("\n");
}
